server:
  port: 8090
  servlet:
    context-path: /com.landkay.springBoot
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  application:
    name: springBoot
  http:
    encoding:
      charset: UTF-8


mybatis:
  mapper-locations: classpath*:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.landkay.springboot.model
  #config-locations: classpath:mybatis-config.xml